// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NfaSporSalonu.Models;

#nullable disable

namespace NfaSporSalonu.Migrations
{
    [DbContext(typeof(NfaSporSalonuDbContext))]
    [Migration("20260425115213_SeedMembershipPlans")]
    partial class SeedMembershipPlans
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NfaSporSalonu.Models.AccessCredential", b =>
                {
                    b.Property<int>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CredentialId"));

                    b.Property<DateTime?>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CredentialType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CredentialValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CredentialId")
                        .HasName("PK__AccessCr__2C58F9CCE609F3FF");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "CredentialValue" }, "UQ__AccessCr__3ED7AE5141FF071B")
                        .IsUnique();

                    b.ToTable("AccessCredentials");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.AccessLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<DateTime?>("AccessTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DenialReason")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId")
                        .HasName("PK__AccessLo__5E548648A9337DDF");

                    b.HasIndex("UserId");

                    b.ToTable("AccessLogs");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.MemberMeasurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasurementId"));

                    b.Property<decimal?>("Bicep")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Chest")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("MeasurementDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Waist")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("MeasurementId")
                        .HasName("PK__MemberMe__85599FB8E86C4A38");

                    b.HasIndex("UserId");

                    b.ToTable("MemberMeasurements");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.MembershipPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("PlanId")
                        .HasName("PK__Membersh__755C22B7CE885E94");

                    b.ToTable("MembershipPlans");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            Category = "Öğrenci",
                            Description = "Öğrenci belgesi ile geçerlidir.",
                            DurationInDays = 30,
                            IsActive = true,
                            PlanName = "Öğrenci 1 Ay",
                            Price = 1100m
                        },
                        new
                        {
                            PlanId = 2,
                            Category = "Öğrenci",
                            Description = "Öğrenci belgesi ile geçerlidir.",
                            DurationInDays = 90,
                            IsActive = true,
                            PlanName = "Öğrenci 3 Ay",
                            Price = 3000m
                        },
                        new
                        {
                            PlanId = 3,
                            Category = "Öğrenci",
                            Description = "Öğrenci belgesi ile geçerlidir. En çok tercih edilen paket!",
                            DurationInDays = 180,
                            IsActive = true,
                            PlanName = "Öğrenci 6 Ay",
                            Price = 5500m
                        },
                        new
                        {
                            PlanId = 4,
                            Category = "Öğrenci",
                            Description = "Öğrenci belgesi ile geçerlidir.",
                            DurationInDays = 365,
                            IsActive = true,
                            PlanName = "Öğrenci 12 Ay",
                            Price = 9000m
                        },
                        new
                        {
                            PlanId = 5,
                            Category = "Sivil",
                            Description = "Tüm spor salonu hizmetlerini kapsar.",
                            DurationInDays = 30,
                            IsActive = true,
                            PlanName = "Sivil 1 Ay",
                            Price = 1200m
                        },
                        new
                        {
                            PlanId = 6,
                            Category = "Sivil",
                            Description = "Tüm spor salonu hizmetlerini kapsar.",
                            DurationInDays = 90,
                            IsActive = true,
                            PlanName = "Sivil 3 Ay",
                            Price = 3250m
                        },
                        new
                        {
                            PlanId = 7,
                            Category = "Sivil",
                            Description = "Tüm spor salonu hizmetlerini kapsar. En çok tercih edilen paket!",
                            DurationInDays = 180,
                            IsActive = true,
                            PlanName = "Sivil 6 Ay",
                            Price = 6000m
                        },
                        new
                        {
                            PlanId = 8,
                            Category = "Sivil",
                            Description = "Tüm spor salonu hizmetlerini kapsar.",
                            DurationInDays = 365,
                            IsActive = true,
                            PlanName = "Sivil 12 Ay",
                            Price = 10000m
                        },
                        new
                        {
                            PlanId = 9,
                            Category = "Pilates",
                            Description = "Reformer Pilates – 8 seanslık paket.",
                            DurationInDays = 60,
                            IsActive = true,
                            PlanName = "Pilates 8 Seans",
                            Price = 2500m
                        },
                        new
                        {
                            PlanId = 10,
                            Category = "Pilates",
                            Description = "Reformer Pilates – 24 seanslık paket. En çok tercih edilen paket!",
                            DurationInDays = 180,
                            IsActive = true,
                            PlanName = "Pilates 24 Seans",
                            Price = 7200m
                        });
                });

            modelBuilder.Entity("NfaSporSalonu.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NotificationType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12385833AA");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UserMembershipId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A385D166C51");

                    b.HasIndex("UserId");

                    b.HasIndex("UserMembershipId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1AF05234AA");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160CD975F2A")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.TrainerNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("MemberId")
                        .HasColumnType("int");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerNotes");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.TrainerTrainee", b =>
                {
                    b.Property<int>("RelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RelationId"));

                    b.Property<DateTime?>("AssignedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("RelationId")
                        .HasName("PK__TrainerT__E2DA16B57A9D6214");

                    b.HasIndex("TraineeId");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerTrainees");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FailedLoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LockoutEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CC119AC61");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105346104D037")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.UserMembership", b =>
                {
                    b.Property<int>("UserMembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserMembershipId"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserMembershipId")
                        .HasName("PK__UserMemb__5A4E736A1750395C");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMemberships");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.WorkoutAndDietProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ProgramType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("ProgramId")
                        .HasName("PK__WorkoutA__7525605805714695");

                    b.HasIndex("TraineeId");

                    b.HasIndex("TrainerId");

                    b.ToTable("WorkoutAndDietPrograms");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.AccessCredential", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.User", "User")
                        .WithMany("AccessCredentials")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__AccessCre__UserI__60A75C0F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.AccessLog", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.User", "User")
                        .WithMany("AccessLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__AccessLog__UserI__656C112C");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.MemberMeasurement", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.User", "User")
                        .WithMany("MemberMeasurements")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__MemberMea__UserI__6E01572D");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.Notification", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Notificat__UserI__76969D2E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.Payment", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Payments__UserId__5AEE82B9");

                    b.HasOne("NfaSporSalonu.Models.UserMembership", "UserMembership")
                        .WithMany("Payments")
                        .HasForeignKey("UserMembershipId")
                        .HasConstraintName("FK__Payments__UserMe__5BE2A6F2");

                    b.Navigation("User");

                    b.Navigation("UserMembership");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.TrainerNote", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.User", "Member")
                        .WithMany("TrainerNotesAsMember")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NfaSporSalonu.Models.User", "Trainer")
                        .WithMany("TrainerNotesAsTrainer")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Member");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.TrainerTrainee", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.User", "Trainee")
                        .WithMany("TrainerTraineeTrainees")
                        .HasForeignKey("TraineeId")
                        .HasConstraintName("FK__TrainerTr__Train__6A30C649");

                    b.HasOne("NfaSporSalonu.Models.User", "Trainer")
                        .WithMany("TrainerTraineeTrainers")
                        .HasForeignKey("TrainerId")
                        .HasConstraintName("FK__TrainerTr__Train__693CA210");

                    b.Navigation("Trainee");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.User", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK__Users__RoleId__4E88ABD4");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.UserMembership", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.MembershipPlan", "Plan")
                        .WithMany("UserMemberships")
                        .HasForeignKey("PlanId")
                        .HasConstraintName("FK__UserMembe__PlanI__571DF1D5");

                    b.HasOne("NfaSporSalonu.Models.User", "User")
                        .WithMany("UserMemberships")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__UserMembe__UserI__5629CD9C");

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.WorkoutAndDietProgram", b =>
                {
                    b.HasOne("NfaSporSalonu.Models.User", "Trainee")
                        .WithMany("WorkoutAndDietProgramTrainees")
                        .HasForeignKey("TraineeId")
                        .HasConstraintName("FK__WorkoutAn__Train__72C60C4A");

                    b.HasOne("NfaSporSalonu.Models.User", "Trainer")
                        .WithMany("WorkoutAndDietProgramTrainers")
                        .HasForeignKey("TrainerId")
                        .HasConstraintName("FK__WorkoutAn__Train__71D1E811");

                    b.Navigation("Trainee");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.MembershipPlan", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.User", b =>
                {
                    b.Navigation("AccessCredentials");

                    b.Navigation("AccessLogs");

                    b.Navigation("MemberMeasurements");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("TrainerNotesAsMember");

                    b.Navigation("TrainerNotesAsTrainer");

                    b.Navigation("TrainerTraineeTrainees");

                    b.Navigation("TrainerTraineeTrainers");

                    b.Navigation("UserMemberships");

                    b.Navigation("WorkoutAndDietProgramTrainees");

                    b.Navigation("WorkoutAndDietProgramTrainers");
                });

            modelBuilder.Entity("NfaSporSalonu.Models.UserMembership", b =>
                {
                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
